workflows:
  android-workflow:
    name: MobiStock Android

    environment:
      java: 17

    scripts:
      - name: Build Debug APK
        script: |
          curl -L https://services.gradle.org/distributions/gradle-8.7-bin.zip -o /tmp/gradle.zip
          unzip -q /tmp/gradle.zip -d /tmp
          /tmp/gradle-8.7/bin/gradle assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
