workflows:
  android-workflow:
    name: MobiStock Android

    environment:
      groups:
        - google_play

      java: 17

    scripts:
      - name: Build Debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
